### ISSUE TITLE
TypeError: this.cssClasses(...).set is not a function

### ISSUE THREAD

**Issue by agrawal-mohit** [triniwiz/nativescript-ng2-socketio-demo#3]
**Environment**
OS X 
tns 2.4.0

**Steps to reproduce**

Clone the repo, goto `nativescript-ng2-socketio-demo' dir
$ npm install
$ tns platform add android
$ tns livesync android --device <device id> --debug

**Behaviour**

> ORIGINAL STACKTRACE:
> JS: TypeError: this.cssClasses(...).set is not a function
> JS:     at ViewUtil.addClass (/data/data/org.nativescript.nativescriptng2socketiodemo/files/app/tns_modules/nativescript-angular/view-util.js:249:31)
> JS:     at NativeScriptRenderer.setElementClass (/data/data/org.nativescript.nativescriptng2socketiodemo/files/app/tns_modules/nativescript-angular/renderer.js:175:27)
> JS:     at DebugAppView._View_LoginComponent0.detectChangesInternal (LoginComponent.template.js:95:19)
> JS:     at DebugAppView.AppView.detectChanges (/data/data/org.nativescript.nativescriptng2socketiodemo/files/app/tns_modules/@angular/core/src/linker/view.js:200:14)
> JS:     at DebugAppView.detectChanges (/data/data/org.nativescript.nativescriptng2socketiodemo/files/app/tns_modules/@angular/core/src/linker/view.js:289:44)
> JS:     at DebugAppView.AppView.detectViewChildrenChanges (/data/data/org.nativescript.nativescriptng2socketiodemo/files/app/tns_modules/@angular/core/src/linker/view.js:220:34)
> JS:     at DebugAppView._View_LoginComponent_Host0.detectChangesInternal (LoginComponent_Host.template.js:30:8)
> JS:     at DebugAppView.AppView.detectChanges (/data/data/org.nativescript.nativescriptng2socketiodemo/files/app/tns_modules/@angular/core/src/linker/view.js:200:14)
> JS:     at DebugAppView.detectChanges (/data/data/org.nativescript.nativescriptng2socketiodemo/files/app/tns_modules/@angular/core/src/linker/view.js:289:44)
> JS:     at DebugAppView.AppView.detectContentChildrenChanges (/data/data/org.nativescript.nativescriptng2socketiodemo/files/app/tns_modules/@angular/core/src/linker/view.js:215:37)
> JS: ERROR CONTEXT:
> JS: [object Object]
> JS: EXCEPTION: Error in components/login/login.html:1:4
> JS: ORIGINAL EXCEPTION: TypeError: this.cssClasses(...).set is not a function
> JS: ORIGINAL STACKTRACE:
> JS: TypeError: this.cssClasses(...).set is not a function
> JS:     at ViewUtil.addClass (/data/data/org.nativescript.nativescriptng2socketiodemo/files/app/tns_modules/nativescript-angular/view-util.js:249:31)
> JS:     at NativeScriptRenderer.setElementClass (/data/data/org.nativescript.nativescriptng2socketiodemo/files/app/tns_modules/nativescript-angular/renderer.js:175:27)
> JS:     at DebugAppView._View_LoginComponent0.detectChangesInternal (LoginComponent.template.js:95:19)
> JS:     at DebugAppView.AppView.detectChanges (/data/data/org.nativescript.nativescriptng2socketiodemo/files/app/tns_modules/@angular/core/src/linker/view.js:200:14)
> JS:     at DebugAppView.detectChanges (/data/data/org.nativescript.nativescriptng2socketiodemo/files/app/tns_modules/@angular/core/src/linker/view.js:289:44)
> JS:     at DebugAppView.AppView.detectViewChildrenChanges (/data/data/org.nativescript.nativescriptng2socketiodemo/files/app/tns_modules/@angular/core/src/linker/view.js:220:34)
> JS:     at DebugAppView._View_LoginComponent_Host0.detectChangesInternal (LoginComponent_Host.template.js:30:8)
> JS:     at DebugAppView.AppView.detectChanges (/data/data/org.nativescript.nativescriptng2socketiodemo/files/app/tns_modules/@angular/core/src/linker/view.js:200:14)
> JS:     at DebugAppView.detectChanges (/data/data/org.nativescript.nativescriptng2socketiodemo/files/app/tns_modules/@angular/core/src/linker/view.js:289:44)
> JS:     at DebugAppView.AppView.detectContentChildrenChanges (/data/data/org.nativescript.nativescriptng2socketiodemo/files/app/tns_modules/@angular/core/src/linker/view.js:215:37)
> JS: ERROR CONTEXT:
> JS: [object Object]
>

**Comment by triniwiz** [comment]
Looks like i need to upgrade the project to 2.4

**Comment by agrawal-mohit** [comment]
Is it because Im using tns 2.4.0 ? Will it help in the meanwhile before you do to downgrade ?

**Comment by triniwiz** [comment]
yeah it will 2.4 change a couple thing with regards to styling

**Comment by agrawal-mohit** [comment]
Is it something you can quickly or do you suggest to work with tns 2.3.0 on this project for now?

**Comment by triniwiz** [comment]
2.3.0 will work fine
